Update the current welcome banner webpart to allow for webpart customization #6
gcxchange-gcechange/custom-welcome-banner pull request #7
Opened 2022-07-14 21:54 UTC by RVany

Resolves #6

2022-07-18 14:29 UTC, RVany commented
I modified the web part according to the description  and uploaded to the dev site (English and French pages)
 **Key points of the update**

- Since the user (who use the web part on their share point site) able to customize all of the content, web part can use for any language not limited to English and French.
- Since all the content of the web part able to customizable, we don't need the localization or preferred language option in property pane. 
- Validation added to make sure  all the fields are not empty.

If above assumptions and used approach are correct README file needs to be modified.

**Questions**
Do we need to do more validation?  specifically, how we can make sure text entered in URL field has valid URL?

2022-07-22 13:08 UTC, Steph4104 requested changes
It all looks good. Only need to delete some comment.

2022-07-22 13:08 UTC, Steph4104 commented on src/webparts/customWelcomeBanner/CustomWelcomeBannerWebPart.ts
> +                //   label: 'Preferred Language',
Pls, delete the comment since we wont need it anymore

2022-07-22 13:08 UTC, Steph4104 commented on src/webparts/customWelcomeBanner/components/CustomWelcomeBanner.tsx
> +    // this.state = {
Pls, remove the comment

2022-07-27 13:32 UTC, Steph4104 approved these changes

2022-07-27 17:18 UTC, merged